#!/usr/bin/env groovy

pipeline {
    agent any

    // options {
    //     buildDiscarder(logRotator(numToKeepStr: '10'))
    //     disableConcurrentBuilds()
    //     timeout(time: 1, unit: 'HOURS')
    //     timestamps()
    // }

    // tools {
    //   dockerTool 'docker-latest'
    // }

    // environment {
    //     IMAGE_VERSION = "${env.BUILD_ID}"
    //     AWS_ECR_REGION = 'ap-southeast-2'
    //     AWS_ECS_SERVICE = 'test-backend-service'
    //     AWS_ECS_TASK_DEFINITION = 'test-backend'
    //     AWS_ECS_COMPATIBILITY = 'FARGATE'
    //     AWS_ECS_NETWORK_MODE = 'awsvpc'
    //     AWS_ECS_CPU = '256'
    //     AWS_ECS_MEMORY = '512'
    //     AWS_ECS_CLUSTER = 'a-comosus-cluster'
    //     AWS_ECS_TASK_DEFINITION_PATH = './CICD/ecs/backend-container-definition-update-image.json'
    // }

    stages {
        stage('build') {
            steps{
                echo "testing from build"
            }

        }

        stage('test') {
            steps{
                echo "testing from test"
            }
        }

        stage('Push Image to ECR') {}

        stage('Deploy in ECS') {}
    }

    post {}
}